- style/styles.css
1. Added responsive design to the main section
the website would look weird in different screen sizes
It makes sure users now can see the website well in different screen sizes
Closes #12
> Cl #12 responsive design

- index.html
- scripts/app.js
- style/styles.css
1. Created Table
2. Created API Function
3. Created Elements
4. Created Rows
5. Appended Rows to ID
Created Table for Modal and Populated from JSON data.
Populates Table from JSON File
Sync Branches
Click Start Pairing and see if results render.
Closes #18
> Tn #18 table filter modal

- index.html
- scripts/app.js
- style/styles.css
1. added select and deselect buttons
i added select and deselect buttons for the filtered data 
it makes sure a user can easily select and deselect interns
Closes #22
> feat(select): select/button

- index.html
- style/styles.css
1. added footer
added footer with mobile responsiveness
Closes #23
> feat: added footer with mobile responisveness

- index.html
- style/styles.css
1. Added Save Button 
2. Fixed Modal Scroll
3. Styled Save Button
Following Figma Design.
Closes #26
> feat(modal): save button/modal scroll

- scripts/app.js
1. fixed select and deselect buttons
whenever the buttons were pressed and the next page was clicked it wouldnt save the edit styles
i adjusted the logic for the select buttons
Closes #27
> Cl #27 fix select buttons

- seedata/interns.json
1. fixed Watsonville name
watsonville was spelled watsonVille
makes the city name accurate
Closes #33
> fix(json):watsonville/name

- index.html
- style/styles.css
1. Save Button => Pair Button
2. Toggles Components
3. Same Department / Same Location
Gives user the option to pair from department or location.
Adds the features.
Closes #32
> feat/fix(toggles): save button text-toggle department/location

- scripts/app.js
1. Change Session Storage from Index to ID
2. Change '' to ""
3. Format changes
4. Made logic easier to read. 
Resolving Future issues with select saving to Session Storage when filtering is implemented.
This changes the session storage saving the Index of the users in the array. Now it saves the ID to the session storage with true as it is selected.
Once filtering is implemented please check if select all and selects are saved with filtering.
Select a user and change the pagination of the table.
I learned how to read through other peoples code and manipulate it to what I want without changing much.
Closes #36
> fix(select): change index to id ss

- index.html
- package-lock.json
- scripts/app.js
- seedata/departments.json
- seedata/locations.json
- style/styles.css
1. added dropdown for location filter
2. added dropdown for department filter
filter interns by department and location
Closes #30
> feat: adding department and location filter

- index.html
- package-lock.json
- scripts/app.js
- seedata/departments.json
- seedata/locations.json
- style/styles.css
1. added search functionality for interns names
make interns searchable by name
##Note 
This branch was made from bm-#30-add-dropdown-options-from-json. So merge that pull request first.
Closes #41
> Bm #41 add search filter

- scripts/app.js
1. Select and Deselect Logic
2. Changed forEach to loop through the filtered interns.
When you filter and select all it will only select the people displayed.
It targets the filtered interns instead of the intern list.
Closes #43
> fix(logic): changed filtered array

- index.html
- scripts/app.js
1. Pairing Functionality
2. Added Id's for DOM
3. Styled Code
Gives the Pairing button functionality and saves it into session storage
See if pairing is save correctly in session storage.
Select users to take out and click pair. Then check session storage.
I learned how to pair people with filters.
Closes #46
> feat(pairing): pairing functionality

- index.html
- style/styles.css
1. Fixed styling for homepage/modal
2. added mobile responsiveness
the homepage/modal neeed to be better styled as well as look better on smaller screen sizes
Closes #47
> feat(responsive):mobile/responsive

- Pages/pairings.html
- scripts/app.js
- scripts/pairingapp.js
- style/styles.css
1. Container for Pairs
2. CSS For Container
3. Logic For Rendering Pairs
4. Created Pages Folder
5. File structure
Display pairing on second page
This allows the user to see the paired teams
Closes #52
> Tn #52 pairing setup

- scripts/app.js
1. fix dropdown options to add "clear"
Closes #49
> refactor: fixing dropdown options

- Pages/pairings.html
- style/styles.css
1. Added styling to the pairing section
the styling was a little off so i fixed the width and padding
makes the site look better
Closes #55
> Cl #55 pairing styling

- index.html
- scripts/app.js
1. Have user select interns they want to pair
2. This is to make the design more intuitive where user will select the interns to pair instead of selecting the interns they don't want to pair.
Closes #61
> feat - select interns to pair

- Pages/pairings.html
- scripts/pairingapp.js
- style/styles.css
- added functionality to download button to download csv file
- styled download button
Closes #58
> Feat: download button style and functionality

- Pages/pairings.html
- scripts/pairingapp.js
- style/styles.css
1. Added edit button functionality
2. made it possible to delete users from pair
3. made it possible to add an unpaired user by search or by list
the edit button had no functionality
this pr will make sure the edit functionality is working properly
Closes #57
> feat(edit):edit/button

- Pages/pairings.html
- index.html
- scripts/app.js
- scripts/pairingapp.js
- style/styles.css
1. Added Reset Button Functionality
2. Reset Modal
3. Reset Modal Functionality - Clears Session Storage and routes you to the main page
4. Created a modal for when not enough people to pair
5. Functionality for modal to pop up when not enough interns.
Gives user the option to reset once pairing is finished
Error handling if user doesn't put enough interns.
Closes #54
> feat(modal): reset modal error modal

- scripts/app.js
1. Fixing Pairing Modal error Logic
Fix logic error
Working under deadlines
> fix(piaring): logic

- Pages/pairings.html
- scripts/app.js
- scripts/pairingapp.js
- style/styles.css
1. Added edge case to allow a popup to let the user knows if there is a team of three created
2. Added padding on the reset button
3. Fixed logic for pairing button
4. Created a warning modal for the edge case
Allows user to know if there is a group of 3
Created and storage a count to know if a group of 3 is created on anther page.
Closes #66
> feat(cases): edge case and fixes

- Pages/pairings.html
- scripts/app.js
- scripts/pairingapp.js
- style/styles.css
1. Created Elements
2. Displayed Accuracy on the second page
3. Dot notation 
4. Added pointer cursor to buttons
5. Added hover affect on reset button
Allows the user to see what percentage of the pairing was accurate with the filters.
Got the session storage information from the first page with the pairing and displayed them onto the second page.
Closes #70
> feat(acc): added accuracy

- scripts/pairingapp.js
- style/styles.css
1. Added styling to the add/delete interns buttons
2. fixed bug that causes added interns to not display their location and department
the problem was no styling was done to the buttons and for the bug issue it was because was only pulling the name and not the object
Closes #67
> feat(button):button/styles

- scripts/pairingapp.js
- style/styles.css
1. added button class to add button 
2. changed teams table margin
changing the styling to make it more appealing
Closes #64
> Feat: fixing pairing button and pairing container margins

- Pages/pairings.html
- style/styles.css
1. Made result table mobile responsive 
2. Made Download and Edit button mobile responsive
Fix result page mobile responsiveness
Closes #75
> feat: adding mobile responsiveness to pairings page

- scripts/app.js
1. Changed Accuracy Logic
Gives Accuracy a better percent 
Closes #77
> feat(logic): accuracy

- style/styles.css
1. Change button in pairing responsiveness
2. Made it width full in screen sizes of 375px
Made mobile screen more appealing
Checked for bugs, none that I could find
Closes #80
> fix(styling): responsiveness for download and edit button
